# -*- coding: utf-8 -*-
"""Analise-dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ii2MfHNA-Q-9_JW26kYz36jwfQAKewg6
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

from google.colab import files
arq = files.upload()

df = pd.read_csv("adm_data.csv")

#verify null values  and other infos in the two dataframes
df.info() 
df.set_index("Serial No.",inplace=True)

df['Research'].sum() # all researchs realized

df["GRE+TOEFL scores"] = df['GRE Score']+df['TOEFL Score']

df.nlargest(10,"GRE+TOEFL scores") # top 10 students by gre and toefl scores

df2 = pd.read_csv("AdventureWorks_Sales_2017.csv")

df2["PeriodinStock"] = (pd.to_datetime(df2["OrderDate"]) - pd.to_datetime(df2["StockDate"])).dt.days #dt.days numeric type

df2.groupby("TerritoryKey")["PeriodinStock"].mean().plot(title="Period in stock by territory")

df2.groupby("TerritoryKey")["PeriodinStock"].mean().plot(title="Period in stock by territory",kind='box') #use of boxplot

df2.groupby(["OrderNumber","CustomerKey"])["OrderQuantity"].sum().sort_values(ascending=False).reset_index() #groupby with list, sort_values and reset_index

df03 = df2[pd.to_datetime(df2["StockDate"]).dt.year == 2003] 
df03.to_csv("stockdate_2003.csv",index=False) # products with stock date year 2003 and save in a csv